notepadProgramFilePath := ""
edgeProgramFilePath := ""
teamsProgramFilePath := ""
vsCodeProgramFilePath := ""
dbeaverProgramFilePath := ""
thunderbirdProgramFilePath := ""
sublimeMergeProgramFilePath := ""
notionProgramFilePath := ""
jmeeterProgramFilePath := ""
linqPad6ProgramFilePath := ""
sublimeTextProgramFilePath := ""
obsidianProgramFilePath := ""
postmanProgramFilePath := ""
wslUbuntuProgramFilePath := ""
lprunpath := ""
ahkHelpWindowProgramPath := ""
cmdProgramFilePath := ""
visualStudio22ProgramFilePath := ""
visualStudio19ProgramFilePath := ""
visualStudio17ProgramFilePath := ""
spotifyFilePath := ""

hostsFilepath := ""

myExcalidrawFilePath := ""
myDrawIOFilePath := ""
mySSHConfigFilePath := ""
myKeysCoreFilePath := ""
myAllDesktopKeysFilePath := ""
myCurrentDesktopKeysFilePath := ""
myLocalSystemVariablesFilePath := ""
myOfficeMailID := ""

NotionWorkLogTodayPage := ""